name: ROS 2 System Controller CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distro: [humble]
        
    container:
      image: osrf/ros:${{ matrix.ros_distro }}-desktop
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup ROS environment
      run: |
        apt-get update
        apt-get install -y python3-colcon-common-extensions python3-rosdep
        rosdep update
        
    - name: Install dependencies
      run: |
        cd /github/workspace
        rosdep install --from-paths src --ignore-src -r -y
        
    - name: Build workspace
      run: |
        cd /github/workspace
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        colcon build --packages-select system_controller
        
    - name: Run unit tests
      run: |
        cd /github/workspace
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        source install/setup.bash
        colcon test --packages-select system_controller --event-handlers console_direct+
        
    - name: Run core class tests (standalone)
      run: |
        cd /github/workspace
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        source install/setup.bash
        ./build/system_controller/test_core_classes --gtest_output=xml:test_results_core.xml
        
    - name: Run regression tests (standalone)
      run: |
        cd /github/workspace  
        source /opt/ros/${{ matrix.ros_distro }}/setup.bash
        source install/setup.bash
        ./build/system_controller/test_regression --gtest_output=xml:test_results_regression.xml
        
    - name: Check test results
      run: |
        cd /github/workspace
        colcon test-result --verbose
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.ros_distro }}
        path: |
          /github/workspace/log/
          /github/workspace/test_results_*.xml
          
  lint:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:humble-desktop
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup ROS environment  
      run: |
        apt-get update
        apt-get install -y python3-colcon-common-extensions
        
    - name: Run linting
      run: |
        cd /github/workspace
        source /opt/ros/humble/setup.bash
        colcon build --packages-select system_controller
        colcon test --packages-select system_controller --ctest-args -R lint
        
  performance:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:humble-desktop
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup ROS environment
      run: |
        apt-get update
        apt-get install -y python3-colcon-common-extensions python3-rosdep time
        rosdep update
        
    - name: Install dependencies and build
      run: |
        cd /github/workspace
        rosdep install --from-paths src --ignore-src -r -y
        source /opt/ros/humble/setup.bash
        colcon build --packages-select system_controller
        
    - name: Run performance benchmarks
      run: |
        cd /github/workspace
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        echo "=== Performance Benchmark Results ===" > performance_report.txt
        echo "Date: $(date)" >> performance_report.txt
        echo "Commit: ${{ github.sha }}" >> performance_report.txt
        echo "" >> performance_report.txt
        
        # Run regression tests which include performance tests
        time ./build/system_controller/test_regression --gtest_filter="*Performance*" >> performance_report.txt 2>&1
        
    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-report
        path: /github/workspace/performance_report.txt
        
  integration:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:humble-desktop
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup ROS environment
      run: |
        apt-get update
        apt-get install -y python3-colcon-common-extensions python3-rosdep
        rosdep update
        
    - name: Build and test full system
      run: |
        cd /github/workspace
        rosdep install --from-paths src --ignore-src -r -y
        source /opt/ros/humble/setup.bash
        colcon build --packages-select system_controller
        
    - name: Run local simulation test
      run: |
        cd /github/workspace
        g++ -std=c++17 -pthread -o run_local_simulation run_local_simulation.cpp
        timeout 30s ./run_local_simulation || true
        echo "Local simulation test completed"
        
    - name: Test system startup
      run: |
        cd /github/workspace
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        
        # Test individual nodes can start (with timeout)
        timeout 10s ros2 run system_controller system_manager_node &
        PID1=$!
        sleep 2
        kill $PID1 || true
        
        timeout 10s ros2 run system_controller command_input_arbiter_node &
        PID2=$!
        sleep 2  
        kill $PID2 || true
        
        echo "Node startup tests completed" 